server:
  http:
    addr: 0.0.0.0
    port: 8000
    timeout: 1s
data:
  postgresql:
    driver: postgresql
    source: root:password@tcp(127.0.0.1:3306)/testdb?parseTime=True
  redis:
    addr: 127.0.0.1:6379
    dial_timeout: 1s
    read_timeout: 0.4s
    write_timeout: 0.6s
  