server:
  http:
    addr: 127.0.0.1:8000
    timeout: 1s
data:
  postgresql:
    driver: pgx
    source: host=127.0.0.1 user=blog_dev password=asdjkl dbname=blog port=5432 sslmode=disable TimeZone=Asia/Shanghai
  redis:
    addr: 101.126.135.143:6379
    dial_timeout: 2s
    read_timeout: 0.4s
    write_timeout: 0.6s
    db: 0
log:
  env: development